--- #YAML:1.0
name:               File-Unpack
version:            0.21
abstract:           An aggressive archive file unpacker, based on mime-types
author:
    - Juergen Weigert <jnw@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    BSD::Resource:        0
    Carp:                 0
    Compress::Raw::Bzip2:  0
    Compress::Raw::Lzma:  0
    Compress::Raw::Zlib:  2.024
    Cwd:                  0
    File::Copy:           0
    File::LibMagic:       0
    File::MimeInfo::Magic:  0
    File::Path:           0
    File::Temp:           0
    Filesys::Statvfs:     0
    IPC::Run:             0
    JSON:                 0
    String::ShellQuote:   0
    Test::More:           0
    Text::Sprintf::Named:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
